<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>IO.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Modules\ResourceManager\ResourceManager\bin\Debug\net9.0\ResourceManager.deps.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.8.0" />
    <PackageReference Include="MySql.Data" Version="9.1.0" />
  </ItemGroup>

</Project>
