////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace IO.Components.Pages
//{
//    using System;


//    /// <summary>
//    ///   A strongly-typed resource class, for looking up localized strings, etc.
//    /// </summary>
//    // This class was auto-generated by the StronglyTypedResourceBuilder
//    // class via a tool like ResGen or Visual Studio.
//    // To add or remove a member, edit your .ResX file then rerun ResGen
//    // with the /str option, or rebuild your VS project.
//    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//    internal partial class Conversation
//    {  // <-- Added 'partial' keyword

//        private static global::System.Resources.ResourceManager resourceMan;

//        private static global::System.Globalization.CultureInfo resourceCulture;

//        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
//        internal Conversation()
//        {
//        }

//        /// <summary>
//        ///   Returns the cached ResourceManager instance used by this class.
//        /// </summary>
//        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
//        internal static global::System.Resources.ResourceManager ResourceManager
//        {
//            get
//            {
//                if (object.ReferenceEquals(resourceMan, null))
//                {
//                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IO.Components.Pages.Conversation", typeof(Conversation).Assembly);
//                    resourceMan = temp;
//                }
//                return resourceMan;
//            }
//        }

//        /// <summary>
//        ///   Overrides the current thread's CurrentUICulture property for all
//        ///   resource lookups using this strongly typed resource class.
//        /// </summary>
//        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
//        internal static global::System.Globalization.CultureInfo Culture
//        {
//            get
//            {
//                return resourceCulture;
//            }
//            set
//            {
//                resourceCulture = value;
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized string similar to Active Chats.
//        /// </summary>
//        internal static string Active_Chats
//        {
//            get
//            {
//                return ResourceManager.GetString("Active Chats", resourceCulture);
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized string similar to Chat ID.
//        /// </summary>
//        internal static string Chat_ID
//        {
//            get
//            {
//                return ResourceManager.GetString("Chat ID", resourceCulture);
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized string similar to Conversation Text.  // <-- Updated Name
//        /// </summary>
//        internal static string Conversation_Text
//        {
//            get
//            {
//                return ResourceManager.GetString("Conversation_Text", resourceCulture);
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized string similar to Download Report.
//        /// </summary>
//        internal static string Download_Report
//        {
//            get
//            {
//                return ResourceManager.GetString("Download Report", resourceCulture);
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized string similar to Message.
//        /// </summary>
//        internal static string Message
//        {
//            get
//            {
//                return ResourceManager.GetString("Message", resourceCulture);
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized string similar to No Conversation have been found.
//        /// </summary>
//        internal static string No_Conversations
//        {
//            get
//            {
//                return ResourceManager.GetString("No Conversations", resourceCulture);
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized string similar to Open Conversation.
//        /// </summary>
//        internal static string Open_Conversation
//        {
//            get
//            {
//                return ResourceManager.GetString("Open Conversation", resourceCulture);
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized string similar to Report Viewer & Downloader.
//        /// </summary>
//        internal static string Report_Viewer___Downloader
//        {
//            get
//            {
//                return ResourceManager.GetString("Report Viewer & Downloader", resourceCulture);
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized string similar to Send Message.
//        /// </summary>
//        internal static string Send_Message
//        {
//            get
//            {
//                return ResourceManager.GetString("Send Message", resourceCulture);
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized string similar to Start Conversation.
//        /// </summary>
//        internal static string Start_Conversation
//        {
//            get
//            {
//                return ResourceManager.GetString("Start Conversation", resourceCulture);
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized string similar to User Email.
//        /// </summary>
//        internal static string User_Email
//        {
//            get
//            {
//                return ResourceManager.GetString("User Email", resourceCulture);
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized string similar to Users.
//        /// </summary>
//        internal static string Users
//        {
//            get
//            {
//                return ResourceManager.GetString("Users", resourceCulture);
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized string similar to Write a Message.
//        /// </summary>
//        internal static string Write_a_Message
//        {
//            get
//            {
//                return ResourceManager.GetString("Write a Message", resourceCulture);
//            }
//        }
//    }
//}